name: ryanolsen
favicon: null
layout_spectrum: 0.6707111299037933
typography_spectrum: 0.9575832686387002
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b8b6b7'
    - '#484941'
    - '#010619'
    - '#f84e1f'
    - '#ff7c44'
  brandStrength: 0.3125
  lightness: 0.3155742615927011
  saturation: 0.7729397714138031
  rhythmicContrast: 0.08610928454436362
purpose: []
